### ISSUE TITLE
Missing translation for "Add Additional Guest"

### ISSUE THREAD

**Issue by dan-chaya** [WPChill/rsvp#33]
Hi

Thank you for this awesome plugin. I've found two issues when adding an additional guest. The first one is that the the button is not being translated. (Even after updating the language files. BTW: These should probably also be updated.) The solution is simple:
On this line:
https://github.com/MachoThemes/WordPress-RSVP-Plugin/blob/8724abc98090dac6b1a02b480e924536510a2f00/rsvp_frontend.inc.php#L413

__( 'Add Additional Guest' ) should be replaced with __( 'Add Additional Guest', 'rsvp-plugin' )

Best regards

**Comment by GuillerVks** [comment]
Replace:

__( 'Add Additional Guest' ) => __( 'Add Additional Guest', 'rsvp-plugin' ) => **__( 'Add a Guest', 'rsvp-plugin' )**

Add a Guest is traslated, Add Additional Guest not.
