### ISSUE TITLE
Floating capital letter N

### ISSUE THREAD

**Issue by Thigis** [WPChill/rsvp#38]
In the RSVP form there is a capital letter N between teh welcome message and teh rsvp question
![image](https://user-images.githubusercontent.com/19376085/81500732-57ae8a80-92d4-11ea-9f8c-4ebe0c70e61f.png)

**Comment by razvanaldea89** [comment]
Think the letter `N` is the personal greeting for the attendee/guest that was entered when guest was added. Same happened to me ( coincidentally I entered `N` also ), after I removed it no more letter `N`
