### ISSUE TITLE
Add checkmark when is posible

### ISSUE THREAD

**Issue by giucu91** [WPChill/rsvp#53]
![image](https://user-images.githubusercontent.com/7580330/111740958-5653d400-888e-11eb-9885-4ad5ccc68074.png)

Everything here is customizable - from events, number of attendees, lists to texts, buttons, titles, and much more. With RSVP Pro, you can customize each slice of your form.

Can be : 

In RSVP PRO everything is customisable : 
- from events
- number of attendees
- Texts
- Buttons
- etc.

**Comment by cristianraiber** [comment]
![image](https://user-images.githubusercontent.com/7841556/111745656-95d1ee80-8895-11eb-9e71-905acc1d8f4e.png)

---

**Comment by cristianraiber** [comment]
"get RSVP PRO" -> sa duca catre pricing page
