### ISSUE TITLE
Unable to change "Sender" from WordPress and not receiving confirmation email 

### ISSUE THREAD

**Issue by mshiemstra** [WPChill/rsvp#56]
I have several WordPress sites and when I receive an email stating there was a new RSVP submission, the sender is from WordPress.  I am unable to find a way to change that so the sender is more specific to the site that has this plugin installed.  It would also be nice for the confirmation email sent to the guests to have a more professional and site specific sender other than just "WordPress".  I am unable to find where to change the sender.  I have tried using a plugin specifically for changing the sender and I have tried manually hardcoding the sender information in both the plugin functions and the WordPress functions, but all that does is break the function so no emails are received at all.

**Comment by razvanaldea89** [comment]
A plugin like https://wordpress.org/plugins/wp-smtp/ should do the trick on this one. You can specify the sender's name and email address. Going to close this.
